[tool.poetry]
name = "chatbot"
version = "0.1.0"
description = ""
authors = ["Yohei <y.meguro.2008@gmail.com>"]

[tool.poetry.dependencies]
langchain = "^0.3.7"
langchain-openai = "^0.2.6"
langchain-core = "^0.3.15"
langgraph = "^0.2.45"